### ISSUE TITLE
Req: Do not run tests on unsupported hardware

### ISSUE THREAD

**Issue by Quackdoc** [nihui/vkpeak#5]
the arc DG2 A380 does not support float64, and this the test should not run, (and probably report unsupported) attached is the related mesa report and vulkan info output for DG2 

https://gitlab.freedesktop.org/mesa/mesa/-/issues/7580

[vkinfo.txt](https://github.com/nihui/vkpeak/files/9893043/vkinfo.txt)

**Comment by nyanmisaka** [comment]
+1 for this. It even crashes the intel UMD driver on Windows.

**Comment by nihui** [comment]
fixed in https://github.com/nihui/vkpeak/releases/tag/20221113
