### ISSUE TITLE
vkpeak crashes at vkMapMemory() on APUs with large dedicated GPU memory allocations set in BIOS (>512MB)

### ISSUE THREAD

**Issue by hjc4869** [nihui/vkpeak#8]
vkpeak tries to allocate 3 ncnn::VkMat instances [here](https://github.com/nihui/vkpeak/blob/820a3cfd54446c9a9bdd7c09f9c8ddece37eb964/vkpeak.cpp#L574C1-L576C58). The allocation size is derived from VulkanDevice::get_heap_budget().

VulkanDevice::get_heap_budget() returns memory budget from the first heap with VK_MEMORY_HEAP_DEVICE_LOCAL_BIT flag. In the case of AMD APUs, this returns the heap representing dedicated GPU memory allocated by the BIOS.

When ncnn::VkMat does the actual allocation however, it uses VkBlobAllocator::fastMalloc(). It handles integrated GPU devices in a [special way](https://github.com/Tencent/ncnn/blob/75e10c6e6157b9c632199a22ae4951a292aa725d/src/allocator.cpp#L740C13-L740C13), specifically requiring VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT and preferring VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT.

As a result, VkMat allocates memory from the 3rd heap with only 256MB of capacity. This causes allocation failures in VkAllocator::allocate_memory() and NULL being passed into [vkMapMemory()](https://github.com/Tencent/ncnn/blob/75e10c6e6157b9c632199a22ae4951a292aa725d/src/allocator.cpp#L760C9-L760C97) in VkBlobAllocator::fastMalloc(), resulting 0xc0000005 in amdvlk64.dll.

There's also potential memory performance issue, as the 256MB (device local | host visible) memory on APUs is not cacheable.

**Comment by nihui** [comment]
hi
please test if this fix works for you https://github.com/Tencent/ncnn/pull/4936

**Comment by hjc4869** [comment]
Tested. It allocated from the expected heap and no longer crashed. Thanks for the fix.

**Comment by nihui** [comment]
fixed release https://github.com/nihui/vkpeak/releases/tag/20230812
